package ipmanager.service;

import org.springframework.cloud.openfeign.FeignClient;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;

import ipmanager.model.Ip;

/**
 * Http client generated by OpenFeign to consume IpAPI 
 * 
 * @see <a href="https://spring.io/projects/spring-cloud-openfeign">Spring Cloud OpenFeign</a>
 * @see <a href="http://ip-api.com">IpAPI</a>
 */

@FeignClient(name = "ip-api", url = "http://ip-api.com/json")
public interface IpApiService {
	/**
	 * <p>This method uses ip-api to retrieve ip informations.</p>
	 * @param query the ip address ex. 25.25.25.25
	 * @return json with ip information to class Ip by OpenFeign module
	 * @see <a href="http://ip-api.com">IpAPI</a>
	 * @since 1.0
	 */
	@GetMapping("/{query}")
	Ip consultIP(@PathVariable("query") String query);
}
