package ipmanager.service;

import org.springframework.cloud.openfeign.FeignClient;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;

import ipmanager.model.Ip;

/**
 * Http client generated by OpenFeign to consume IpAPI .
 * 
 * @see <a
 *      href="https://spring.io/projects/spring-cloud-openfeign>Spring Cloud OpenFeign</a>"
 * @see <a
 *      href="https://viacep.com.br>IpAPI</a>"
 */

@FeignClient(name = "ip-api", url = "http://ip-api.com/json")
public interface IpApiService {
	@GetMapping("/{query}")
	Ip consultIP(@PathVariable("query") String query);
}
